### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by MarcoZehe** [zutrinken/attila#119]
I am currently migrating to Ghost and was recommended the Attila theme by one of the support staff when I ran into pagination problems with the original Caspar theme. I am blind and use a screen reader.

While trying out Attila, I found a few issues, which I will be submitting a pull request for shortly. These are:

- [x] The social links at the top have duplicated titles, and the icons aren't properly hidden from screen readers.
- [x] The menu button is not a button, and the close button is inaccessible.
- [x] The social sharing links below a post don't talk well with a screen reader.
- [x] The pagination navigation is in a doubly nested navigation landmark.
- [x] The arrows for previous and next post (when going by single posts) don't talk.

## Things to also consider changing

- Don't rely on placeholders alone as form labeling technique, see [Don't use the placeholder attribute](https://www.smashingmagazine.com/2018/06/placeholder-attribute/).

## Questions

@zutrinken Why is there a role "presentation" on the list items in the navigation partial? Why do you want to hide that from a screen reader?

Also, why did you [hide](https://github.com/zutrinken/attila/commit/2ee37986b28445c9bb274f6ad5d92bc485311a92#diff-da725cf4823250b3f76285b47c77ac46R1050) the span that contains the social media link text in the navigation rewrite? Items with display:none; aren't picked up by screen readers, either, so as far as I can see, this span is now completely superfluous.

**Comment by zutrinken** [comment]
Thanks a lot for your contribution!

I actually don't remember why the role presentation was there. I removed it. The navigation had the labels, because I thought about showing them on mobile, when the menu layout changes, but in the end I didn't. So removed them as well.

The placeholder issue I save for when Ghost implements search as a core feature. The current implementation is rather experimental anyways.
