### ISSUE TITLE
Add tags list page

### ISSUE THREAD

**Issue by koznov** [zutrinken/attila#149]
Hello @zutrinken !

Thanks for the great theme, it's awesome.

Can we get also an additional template page into theme with all tags with preview (a theme that contains this functionality is liebling)?
You have got this function in search (in default.hbs):

```
{{#get 'tags' limit='all' include='count.posts' order='count.posts desc'}}
	{{#foreach tags}}
		<a href='{{ url }}'>{{ name }}: {{ count.posts }}</a>
	{{/foreach}}
{{/get}}
```
Example how this looks like in liebling theme:
![image](https://user-images.githubusercontent.com/16073136/94012579-a9524000-fdb1-11ea-872b-e182c9d4a194.png)

**Comment by zutrinken** [comment]
Hi @koznov ... sorry for late reply, have been on the road for a while.

As you noticed, there's a basic overview when search is activated. I see that position as the smartest, since it gives you inspiration when you consider searching for something but might feel stuck. I just rebuild the whole search:

<img width="1218" alt="Screenshot 2020-12-30 at 14 25 45" src="https://user-images.githubusercontent.com/888679/103354175-1eb56700-4aab-11eb-96ab-bc5bd163b963.png">

The overview template itself I find a little pointless. I'd rather see categories listed in the main navigation instead of an extra site.

Nonetheless I could imagine having a small overview on the front page instead. I'll keep that in mind for the future.

Thanks for your input!
