### ISSUE TITLE
Need an easier way to use old (non-native) search function

### ISSUE THREAD

**Issue by mkh4lili** [zutrinken/attila#232]
Ghost’s native search function was supported by Attila a few versions ago. The problem is the original search function, built into Attila, was smarter and much more useful. As of writing, the native version still doesn’t index post content, and I’m not sure when it will.

So, I propose giving a way for users to easily switch back to the original search instead of native (if there is one, I can’t figure it out). At least outlining it in the readme file, telling us which lines to comment out etc.

When Ghost’s native search is upgraded, of course, this will no longer be necessary... but for today it would be a good bridging step.

**Comment by frankie-mceyes** [comment]
Hello!
I just tried to do a content search on my Ghost site and the native search did find out the post content, instead of the title/tags.
Screenshot attached:
![image](https://user-images.githubusercontent.com/45453358/186616576-b12678aa-45c9-40b8-98ec-24b7a4105eb7.png)

What happens if you try to search a piece of text that you know is inside a post?

**Comment by mkh4lili** [comment]
Hi there!

> What happens if you try to search a piece of text that you know is inside a post?

Strange - it doesn’t work for me. Here is a search for the word ‘lobbying’ on [my site](https://subvrt.org) just now, with native search on the left and Attila’s original search on the right.

You’ll see the latter (correctly) finds four posts with this term, which doesn’t appear in the tags or excerpts.
<img width="1398" alt="Screenshot 2022-08-25 at 12 00 42" src="https://user-images.githubusercontent.com/81428183/186622678-cce88717-34c6-4c95-ad3d-95d5455b3fcd.png">

In their [changelog](https://ghost.org/changelog/search/), the Ghost team says native search doesn’t yet index posts:

> It still comes with a few limitations, though. The search feature indexes post titles, excerpts, authors and tags - but it does not search across post content

... so I’d be surprised if they implemented this already. But still curious why it works for you?

**Comment by frankie-mceyes** [comment]
Ok, that was a bad from my side. I looked for words that were in the first one/two paragraphs of my articles, but I totally forgot that the Ghost search indexes excerpts. Since I don't make custom excerpts, Ghost takes the first paragraphs and labels them automatically as the article excerpt.
I just tried a sentence from the **bottom** of one of my article and, as expected, Search was not able to find anything.

Thanks for letting me know this, that slipped out of my sight 🥲
I will rollback to Attila Search for now.
