### ISSUE TITLE
Zip files at maximum compression by default

### ISSUE THREAD

**Issue by beleidy** [zutrinken/attila#61]
When using `grunt zip` the resulting file size is currently 1.5MB. This is larger than the default ghost upload file size limit setting for some deployment setups, including the official docker image. 

While it is up to the user to change their default upload size limit, the problem could be avoided if zipping the theme was at full compression. 

On a linux machine, I extracted the resulting zip file and rezipped it with
```
zip -r9 attila-9.zip *
```
The resulting file sizes
```
-rw-r--r-- 1 amr amr  822694 Apr 20 09:50 attila-9.zip
-rw-r--r-- 1 amr amr 1464593 Apr 20 09:38 attila.zip
```

I checked `Gruntfile.js` and could not see a quick way to change that and submit a MR. Happy to do so if you can point me to the right place. Thank you.

**Comment by deadlysyn** [comment]
grunt-zip doesn't support compression by default, but a PR could easily fix that by passing options to the wrapped jszip (jszip does support compression options; https://stuk.github.io/jszip/documentation/api_jszip/file_data.html)... but while researching that I finally noticed #80 which just pulled in grunt-contrib-compress so it seems this issue is stale. :-)

**Comment by beleidy** [comment]
Thanks for following up on the issue :)
